# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6c5a428922a089eea37a5f32900d9d70376e9766046a4d8ca8a26755d99f0ceea37088609b0f3bea86df7d5cbb92e1d9217af3ddb4a7f74587547f2a6c574e

test:
  secret_key_base: 6b4c0b435cb250397ddd9576ff1ccb2183b7c74b637c7d9fa2aa618b306c4641f6e95997fcc4600c17aa1a8e3a9cc234a2ee2ead51789827346714e61ce83bb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
